name: Portable Preferences PoC

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  poc:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15, macos-26]
    steps:
      ## Environment setup

      - uses: actions/checkout@v6

      - name: Setup OS for VO automation
        uses: guidepup/setup-action@0.21.0

      ## Example global defaults

      - name: Disable Splash
        run: |
          defaults write com.apple.VoiceOverTraining doNotShowSplashScreen -bool true || true

      - name: Enable AppleScript Control
        run: |
          defaults write com.apple.VoiceOver4/default SCREnableAppleScript -bool true || true

      - name: Set Default Greeting
        run: |
          defaults write com.apple.VoiceOver4/default loginGreeting -string "Default Greeting" || true

      ## Ensure VO initialised at least once

      - name: Open & Close VoiceOver VoiceOver Utility
        run: |
          mkdir -p artifacts || true
          /usr/bin/osascript start-vo-utility.applescript || true
          sleep 5
          screencapture artifacts/utility.png || true
          /usr/bin/osascript stop-vo-utility.applescript || true

      - name: Start & Stop VoiceOver
        run: |
          /System/Library/CoreServices/VoiceOver.app/Contents/MacOS/VoiceOverStarter &
          sleep 5
          mkdir -p artifacts || true
          screencapture artifacts/started.png || true
          kill -15 $(ps aux | egrep "[V]oiceOver.app/Contents/MacOS/VoiceOver launchd -s" | awk '{print $2}')
          /usr/bin/osascript stop-vo.applescript || true
          sleep 5
          screencapture artifacts/stopped.png || true

      ## Portable preferences setup

      - name: Inject unique login greeting into portable preference
        id: greeting
        run: |
          SECRET=$(uuidgen)-$(openssl rand -hex 16)

          DEFAULT_PLIST="./${{ matrix.os }}/VoiceOver/VoiceOver4.portable/default.plist"

          /usr/libexec/PlistBuddy \
            -c "Delete :loginGreeting" \
            "$DEFAULT_PLIST" 2>/dev/null || true

          /usr/libexec/PlistBuddy \
            -c "Add :loginGreeting string $SECRET" \
            "$DEFAULT_PLIST"

          echo "secret=$SECRET" >> "$GITHUB_OUTPUT"

          echo "Injected loginGreeting:"
          /usr/libexec/PlistBuddy \
            -c "Print :loginGreeting" \
            "$DEFAULT_PLIST"

      - name: Convert plist xml to binary
        run: |
          plutil -convert binary1 "./${{ matrix.os }}/VoiceOver/VoiceOver4.portable/default.plist"
          plutil -convert binary1 "./${{ matrix.os }}/VoiceOver/VoiceOver4.portable/master.plist"

      - name: Create VoiceOverPreferences.dmg from "./${{ matrix.os }}/VoiceOver/VoiceOver4.portable"
        run: |
          hdiutil create \
            -srcfolder "./${{ matrix.os }}/VoiceOver/VoiceOver4.portable" \
            -size 256m \
            -fs APFS \
            -volname VoiceOverPreferences \
            -ov \
            VoiceOverPreferences.dmg

      - name: Attach portable preferences
        run: |
          hdiutil attach \
            VoiceOverPreferences.dmg \
            -mountpoint /Volumes/VoiceOverPreferences

      - name: Verify mount
        run: |
          ls -R /Volumes/VoiceOverPreferences
          test -f /Volumes/VoiceOverPreferences/default.plist
          test -f /Volumes/VoiceOverPreferences/master.plist
          test -f /Volumes/VoiceOverPreferences/voidentifier

      ## Temp portable preferences enablement

      - name: Enable portable preferences in VO
        run: |
          /usr/bin/osascript start-portable-preferences.applescript || true

      ## Automated portable preferences enablement

      - name: Read portable identifier
        id: portable
        run: |
          IDENTIFIER=$(
            /usr/libexec/PlistBuddy \
              -c "Print :identifier" \
              "./${{ matrix.os }}/VoiceOver/VoiceOver4.portable/voidentifier"
          )
          echo "identifier=$IDENTIFIER" >> "$GITHUB_OUTPUT"

      - name: Trust portable preferences 1
        env:
          IDENTIFIER: ${{ steps.portable.outputs.identifier }}
        run: |
          PLIST="$HOME/Library/Preferences/com.apple.VoiceOver4.local.plist"

          # Ensure plist exists
          plutil -create binary1 "$PLIST" 2>/dev/null || true

          # lastTouchedKey
          /usr/libexec/PlistBuddy -c "Delete :lastTouchedKey" "$PLIST" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :lastTouchedKey string $IDENTIFIER" "$PLIST"

          # SCRCUserDefaultsAlwaysUsePortableIDs
          /usr/libexec/PlistBuddy -c "Print :SCRCUserDefaultsAlwaysUsePortableIDs" "$PLIST" >/dev/null 2>&1 || {
            /usr/libexec/PlistBuddy -c "Add :SCRCUserDefaultsAlwaysUsePortableIDs array" "$PLIST"
          }

          # portablePreferenceKeys
          /usr/libexec/PlistBuddy -c "Print :portablePreferenceKeys" "$PLIST" >/dev/null 2>&1 || {
            /usr/libexec/PlistBuddy -c "Add :portablePreferenceKeys array" "$PLIST"
          }

          # append if missing
          for KEY in \
            SCRCUserDefaultsAlwaysUsePortableIDs \
            portablePreferenceKeys
          do
            if ! /usr/libexec/PlistBuddy -c "Print :$KEY" "$PLIST" | grep -Fxq "$IDENTIFIER"; then
              INDEX=$(
                /usr/libexec/PlistBuddy -c "Print :$KEY" "$PLIST" |
                tail -n +2 |
                wc -l |
                tr -d ' '
              )

              /usr/libexec/PlistBuddy -c "Add :$KEY:$INDEX string $IDENTIFIER" "$PLIST"
            fi
          done

      - name: Dump local preferences 1
        run: |
          plutil -p "$HOME/Library/Preferences/com.apple.VoiceOver4.local.plist"

      - name: Trust portable preferences 2
        env:
          IDENTIFIER: ${{ steps.portable.outputs.identifier }}
        run: |
          PLIST="$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4.local.plist"

          # Ensure directory exists
          mkdir -p "$(dirname "$PLIST")"

          # Ensure plist exists
          plutil -create binary1 "$PLIST" 2>/dev/null || true

          # lastTouchedKey
          /usr/libexec/PlistBuddy -c "Delete :lastTouchedKey" "$PLIST" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :lastTouchedKey string $IDENTIFIER" "$PLIST"

          # SCRCUserDefaultsAlwaysUsePortableIDs
          /usr/libexec/PlistBuddy -c "Print :SCRCUserDefaultsAlwaysUsePortableIDs" "$PLIST" >/dev/null 2>&1 || {
            /usr/libexec/PlistBuddy -c "Add :SCRCUserDefaultsAlwaysUsePortableIDs array" "$PLIST"
          }

          # portablePreferenceKeys
          /usr/libexec/PlistBuddy -c "Print :portablePreferenceKeys" "$PLIST" >/dev/null 2>&1 || {
            /usr/libexec/PlistBuddy -c "Add :portablePreferenceKeys array" "$PLIST"
          }

          # append if missing
          for KEY in \
            SCRCUserDefaultsAlwaysUsePortableIDs \
            portablePreferenceKeys
          do
            if ! /usr/libexec/PlistBuddy -c "Print :$KEY" "$PLIST" | grep -Fxq "$IDENTIFIER"; then
              INDEX=$(
                /usr/libexec/PlistBuddy -c "Print :$KEY" "$PLIST" |
                tail -n +2 |
                wc -l |
                tr -d ' '
              )

              /usr/libexec/PlistBuddy -c "Add :$KEY:$INDEX string $IDENTIFIER" "$PLIST"
            fi
          done

      - name: Dump local preferences 2
        run: |
          plutil -p "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4.local.plist"

      ## File Verification Stages

      - name: Preferences List
        run: |
          ls -la "$HOME/Library/Preferences/" || true

      - name: com.apple.VoiceOver4 Preferences List
        run: |
          ls -la "$HOME/Library/Preferences/com.apple.VoiceOver4" || true

      - name: Group Containers List
        run: |
          ls -la "$HOME/Library/Group Containers/" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Application Scripts" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Application Support" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Caches" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences/" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4/" || true

      - name: Accessibility List
        run: |
          ls -la "/private/var/db/Accessibility/" || true
          cat "/private/var/db/Accessibility/.VoiceOverAppleScriptEnabled" || true
          cat "/private/var/db/Accessibility/.VoiceOverAppleScriptEnabled-Migrated" || true

      - name: com.apple.VoiceOver4/default.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4/default.plist" || true

      - name: com.apple.VoiceOver4/defaultValue.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4/defaultValue.plist" || true

      - name: com.apple.VoiceOver4/master.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4/master.plist" || true

      - name: com.apple.VoiceOver.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver.plist" || true

      - name: com.apple.VoiceOver4.local.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4.local.plist" || true

      - name: com.apple.VoiceOverTraining.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOverTraining.plist" || true

      - name: com.apple.VoiceOverUtility.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOverUtility.plist" || true

      - name: com.apple.VoiceOverUtilityCacheBuilder.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOverUtilityCacheBuilder.plist" || true

      - name: group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4/default.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4/default.plist" || true

      - name: group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4.local.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4.local.plist" || true

      - name: group.com.apple.VoiceOver/.com.apple.containermanagerd.metadata.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Group Containers/group.com.apple.VoiceOver/.com.apple.containermanagerd.metadata.plist" || true

      ## VO Verification Stages

      - name: Launch & Verify VoiceOver Utility
        run: |
          mkdir -p artifacts || true
          /usr/bin/osascript start-vo-utility.applescript || true

          sleep 5

          screencapture artifacts/utility.png || true
          /usr/bin/osascript stop-vo-utility.applescript || true

          sleep 5

      - name: Launch & Verify VoiceOver Welcome Greeting
        env:
          EXPECTED: ${{ steps.greeting.outputs.secret }}
        run: |
          # Disable splash screen
          defaults write com.apple.VoiceOverTraining doNotShowSplashScreen -bool true

          sleep 1

          mkdir -p artifacts || true

          # Start VoiceOver
          /System/Library/CoreServices/VoiceOver.app/Contents/MacOS/VoiceOverStarter &

          for i in {1..50}; do
            echo "Attempt: $i"
            screencapture artifacts/vo-$i.png || true
            ACTUAL=$(/usr/bin/osascript voiceOverPerform.applescript 2>/dev/null || true)
            echo "Spoken Phrase: $ACTUAL"

            if [ "$ACTUAL" = "$EXPECTED" ]; then
              break
            fi

            sleep 0.1
          done

          echo "Expected: $EXPECTED"
          echo "Actual:   $ACTUAL"
          test "$ACTUAL" = "$EXPECTED"

      ## Cleanup

      - name: Cleanup
        if: always()
        run: |
          kill -15 $(ps aux | egrep "[V]oiceOver.app/Contents/MacOS/VoiceOver launchd -s" | awk '{print $2}')
          /usr/bin/osascript stop-vo.applescript || true
          hdiutil detach /Volumes/VoiceOverPreferences || true
          rm -f VoiceOverPreferences.dmg || true

      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            **/artifacts/**/*
