name: Portable Preferences PoC

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  poc:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15, macos-26]
    steps:
      ## Environment setup

      - uses: actions/checkout@v6

      - name: Setup OS for VO automation
        uses: guidepup/setup-action@0.21.0

      ## Example global defaults

      - name: Disable Splash
        run: |
          defaults write com.apple.VoiceOverTraining doNotShowSplashScreen -bool true || true

      - name: Enable AppleScript Control
        run: |
          defaults write com.apple.VoiceOver4/default SCREnableAppleScript -bool true || true

      - name: Set Default Greeting
        run: |
          defaults write com.apple.VoiceOver4/default loginGreeting -string "Default Greeting" || true

      - name: Start & Stop VoiceOver
        run: |
          /System/Library/CoreServices/VoiceOver.app/Contents/MacOS/VoiceOverStarter &
          sleep 5
          kill -15 $(ps aux | egrep "[V]oiceOver.app/Contents/MacOS/VoiceOver launchd -s" | awk '{print $2}') || true
          sleep 5
          /usr/bin/osascript stop-vo.applescript || true

      ## Portable preferences setup

      # - name: Inject unique login greeting into portable preference
      #   id: greeting
      #   run: |
      #     SECRET=guidepup-$(uuidgen)-$(openssl rand -hex 16)

      #     DEFAULT_PLIST="./${{ matrix.os }}/VoiceOver/VoiceOver4.portable/default.plist"

      #     /usr/libexec/PlistBuddy \
      #       -c "Delete :loginGreeting" \
      #       "$DEFAULT_PLIST" 2>/dev/null || true

      #     /usr/libexec/PlistBuddy \
      #       -c "Add :loginGreeting string $SECRET" \
      #       "$DEFAULT_PLIST"

      #     echo "secret=$SECRET" >> "$GITHUB_OUTPUT"

      #     echo "Injected loginGreeting:"
      #     /usr/libexec/PlistBuddy \
      #       -c "Print :loginGreeting" \
      #       "$DEFAULT_PLIST"

      - name: Convert plist xml to binary
        run: |
          plutil -convert binary1 "./${{ matrix.os }}/VoiceOver/VoiceOver4.portable/default.plist"
          plutil -convert binary1 "./${{ matrix.os }}/VoiceOver/VoiceOver4.portable/master.plist"

      - name: Create Volume
        run: |
          hdiutil create \
            -size 256m \
            -fs APFS \
            -volname GuidepupVoiceOverPreferences \
            -ov \
            GuidepupVoiceOverPreferences.dmg

          hdiutil attach \
            GuidepupVoiceOverPreferences.dmg \
            -mountpoint /Volumes/GuidepupVoiceOverPreferences

          cp -r "./${{ matrix.os }}/" /Volumes/GuidepupVoiceOverPreferences/

      - name: Verify mount
        run: |
          ls -R /Volumes/GuidepupVoiceOverPreferences

      ## Automated portable preferences enablement

      - name: Read portable identifier
        id: portable
        run: |
          IDENTIFIER=$(
            /usr/libexec/PlistBuddy \
              -c "Print :identifier" \
              "./${{ matrix.os }}/VoiceOver/VoiceOver4.portable/voidentifier"
          )
          echo "identifier=$IDENTIFIER" >> "$GITHUB_OUTPUT"

      - name: Trust portable preferences - global preferences
        env:
          IDENTIFIER: ${{ steps.portable.outputs.identifier }}
        run: |
          PLIST="$HOME/Library/Preferences/com.apple.VoiceOver4.local.plist"

          # Ensure plist exists
          plutil -create binary1 "$PLIST" 2>/dev/null || true

          # lastTouchedKey
          /usr/libexec/PlistBuddy -c "Delete :lastTouchedKey" "$PLIST" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :lastTouchedKey string $IDENTIFIER" "$PLIST"

          # SCRCUserDefaultsAlwaysUsePortableIDs
          /usr/libexec/PlistBuddy -c "Print :SCRCUserDefaultsAlwaysUsePortableIDs" "$PLIST" >/dev/null 2>&1 || {
            /usr/libexec/PlistBuddy -c "Add :SCRCUserDefaultsAlwaysUsePortableIDs array" "$PLIST"
          }

          # portablePreferenceKeys
          /usr/libexec/PlistBuddy -c "Print :portablePreferenceKeys" "$PLIST" >/dev/null 2>&1 || {
            /usr/libexec/PlistBuddy -c "Add :portablePreferenceKeys array" "$PLIST"
          }

          # append if missing
          for KEY in \
            SCRCUserDefaultsAlwaysUsePortableIDs \
            portablePreferenceKeys
          do
            if ! /usr/libexec/PlistBuddy -c "Print :$KEY" "$PLIST" | grep -Fxq "$IDENTIFIER"; then
              INDEX=$(
                /usr/libexec/PlistBuddy -c "Print :$KEY" "$PLIST" |
                tail -n +2 |
                wc -l |
                tr -d ' '
              )

              /usr/libexec/PlistBuddy -c "Add :$KEY:$INDEX string $IDENTIFIER" "$PLIST"
            fi
          done

      - name: Trust portable preferences - group container preferences
        env:
          IDENTIFIER: ${{ steps.portable.outputs.identifier }}
        run: |
          PLIST="$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4.local.plist"

          # Ensure directory exists
          mkdir -p "$(dirname "$PLIST")"

          # Ensure plist exists
          plutil -create binary1 "$PLIST" 2>/dev/null || true

          # lastTouchedKey
          /usr/libexec/PlistBuddy -c "Delete :lastTouchedKey" "$PLIST" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :lastTouchedKey string $IDENTIFIER" "$PLIST"

          # SCRCUserDefaultsAlwaysUsePortableIDs
          /usr/libexec/PlistBuddy -c "Print :SCRCUserDefaultsAlwaysUsePortableIDs" "$PLIST" >/dev/null 2>&1 || {
            /usr/libexec/PlistBuddy -c "Add :SCRCUserDefaultsAlwaysUsePortableIDs array" "$PLIST"
          }

          # portablePreferenceKeys
          /usr/libexec/PlistBuddy -c "Print :portablePreferenceKeys" "$PLIST" >/dev/null 2>&1 || {
            /usr/libexec/PlistBuddy -c "Add :portablePreferenceKeys array" "$PLIST"
          }

          # append if missing
          for KEY in \
            SCRCUserDefaultsAlwaysUsePortableIDs \
            portablePreferenceKeys
          do
            if ! /usr/libexec/PlistBuddy -c "Print :$KEY" "$PLIST" | grep -Fxq "$IDENTIFIER"; then
              INDEX=$(
                /usr/libexec/PlistBuddy -c "Print :$KEY" "$PLIST" |
                tail -n +2 |
                wc -l |
                tr -d ' '
              )

              /usr/libexec/PlistBuddy -c "Add :$KEY:$INDEX string $IDENTIFIER" "$PLIST"
            fi
          done

      - name: Create portable preferences symlinks
        run: |
          VO_PORTABLE="/Volumes/GuidepupVoiceOverPreferences/VoiceOver/VoiceOver4.portable"
          GLOBAL_PREFS="$HOME/Library/Preferences"
          GROUP_CONTAINER_PREFS="$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences"

          ln -sf "$VO_PORTABLE" "$GLOBAL_PREFS/com.apple.VoiceOver4.portable.scrd"
          ln -sf "$VO_PORTABLE" "$GLOBAL_PREFS/com.apple.VoiceOver4.portable.scrd.vou"
          ln -sf "$VO_PORTABLE" "$GLOBAL_PREFS/com.apple.VoiceOver4.portable.scro"
          ln -sf "$VO_PORTABLE" "$GROUP_CONTAINER_PREFS/com.apple.VoiceOver4.portable.scrd"
          ln -sf "$VO_PORTABLE" "$GROUP_CONTAINER_PREFS/com.apple.VoiceOver4.portable.scrd.vou"
          ln -sf "$VO_PORTABLE" "$GROUP_CONTAINER_PREFS/com.apple.VoiceOver4.portable.scro"

      ## Verification Stages

      - name: Launch & Verify VoiceOver Welcome Greeting
        run: |
          mkdir -p artifacts || true

          # Start VoiceOver
          /System/Library/CoreServices/VoiceOver.app/Contents/MacOS/VoiceOverStarter &

          for i in {1..20}; do
            echo "Attempt: $i"
            screencapture artifacts/vo-$i.png || true
            ACTUAL=$(/usr/bin/osascript voiceOverPerform.applescript 2>/dev/null || true)
            echo "Spoken Phrase: $ACTUAL"
            sleep 0.01
          done

          kill -15 $(ps aux | egrep "[V]oiceOver.app/Contents/MacOS/VoiceOver launchd -s" | awk '{print $2}') || true
          sleep 5
          /usr/bin/osascript stop-vo.applescript || true

      - name: Preferences List
        run: |
          ls -la "$HOME/Library/Preferences/" || true

      - name: Group Containers List
        run: |
          ls -la "$HOME/Library/Group Containers/" || true
          ls -laR "$HOME/Library/Group Containers/group.com.apple.VoiceOver/" || true

      ## Cleanup

      - name: Cleanup
        if: always()
        run: |
          hdiutil detach /Volumes/GuidepupVoiceOverPreferences || true
          rm -f GuidepupVoiceOverPreferences.dmg || true

      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            **/artifacts/**/*
