name: Read VoiceOver Group Container

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  read:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15, macos-26]

    steps:
      - name: Disable Splash
        run: |
          defaults write com.apple.VoiceOverTraining doNotShowSplashScreen -bool true || true

      - name: Enable AppleScript Control
        run: |
          defaults write com.apple.VoiceOver4/default SCREnableAppleScript -bool true || true

      - name: Disable Automatically Speaking Web Page
        run: |
          defaults write com.apple.VoiceOver4/default SCRCUserDefaultsAutomaticallySpeakWebPage -bool false || true

      - name: Start & Stop VoiceOver
        run: |
          /System/Library/CoreServices/VoiceOver.app/Contents/MacOS/VoiceOverStarter &

          sleep 5

          mkdir -p artifacts || true
          screencapture artifacts/started.png || true

          kill -15 $(ps aux | egrep "[V]oiceOver.app/Contents/MacOS/VoiceOver launchd -s" | awk '{print $2}')

          sleep 5

          screencapture artifacts/stopped.png || true

      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            **/artifacts/**/*

      - name: Preferences List
        run: |
          ls -la "$HOME/Library/Preferences/" || true

      - name: com.apple.VoiceOver4 Preferences List
        run: |
          ls -la "$HOME/Library/Preferences/com.apple.VoiceOver4" || true

      - name: Group Containers List
        run: |
          ls -la "$HOME/Library/Group Containers/" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Application Scripts" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Application Support" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Caches" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences/" || true
          ls -la "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4/" || true

      - name: Accessibility List
        run: |
          ls -la "/private/var/db/Accessibility/" || true
          cat "/private/var/db/Accessibility/.VoiceOverAppleScriptEnabled" || true
          cat "/private/var/db/Accessibility/.VoiceOverAppleScriptEnabled-Migrated" || true

      - name: com.apple.VoiceOver4/default.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4/default.plist" || true

      - name: com.apple.VoiceOver4/defaultValue.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4/defaultValue.plist" || true

      - name: com.apple.VoiceOver4/master.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4/master.plist" || true

      - name: com.apple.VoiceOver.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver.plist" || true

      - name: com.apple.VoiceOver4.local.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4.local.plist" || true

      - name: com.apple.VoiceOverTraining.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOverTraining.plist" || true

      - name: com.apple.VoiceOverUtility.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOverUtility.plist" || true

      - name: com.apple.VoiceOverUtilityCacheBuilder.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOverUtilityCacheBuilder.plist" || true

      - name: group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4/default.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4/default.plist" || true

      - name: group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4.local.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Group Containers/group.com.apple.VoiceOver/Library/Preferences/com.apple.VoiceOver4.local.plist" || true

      - name: group.com.apple.VoiceOver/.com.apple.containermanagerd.metadata.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Group Containers/group.com.apple.VoiceOver/.com.apple.containermanagerd.metadata.plist" || true
