name: Read VoiceOver Group Container

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  read:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15, macos-26]

    steps:
      - name: Preferences List
        run: |
          ls -la "$HOME/Library/Preferences/" || true

      - name: com.apple.VoiceOver4/default.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4/default.plist" || true

      - name: com.apple.VoiceOver4/defaultValue.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4/defaultValue.plist" || true

      - name: com.apple.VoiceOver4/master.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4/master.plist" || true

      - name: com.apple.VoiceOver.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver.plist" || true

      - name: com.apple.VoiceOver4.local.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOver4.local.plist" || true

      - name: com.apple.VoiceOverTraining.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOverTraining.plist" || true

      - name: com.apple.VoiceOverUtility.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOverUtility.plist" || true

      - name: com.apple.VoiceOverUtilityCacheBuilder.plist
        run: |
          plutil -convert xml1 -o - "$HOME/Library/Preferences/com.apple.VoiceOverUtilityCacheBuilder.plist" || true
